### ISSUE TITLE
semilog plots

### ISSUE THREAD

**Issue by dpo** [sunetos/TextPlots.jl#3]
I'm sure your todo list is already quite long, but `semilogy()` would be a great addition. Currently, TextPlots is infinitely faster than Gadfly.

**Comment by sunetos** [comment]
I just committed a rough first stab at this. It doesn't show the scale on the axis with tick marks or anything, and it has bugs at the boundaries, but it seems like it's working otherwise. If you could give it a try (use the new logplot() function) against HEAD: Pkg.clone("https://github.com/sunetos/TextPlots.jl.git")

And let me know if that's what you had in mind?
